GO 
USE SP_HR

GO
CREATE TABLE Genders(
[Id] INT IDENTITY PRIMARY KEY,
[Type] NVARCHAR (50) UNIQUE NOT NULL 
)

GO
INSERT INTO StateWorkTypes VALUES (N'Kişi')
INSERT INTO StateWorkTypes VALUES (N'Qadın')
