INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (221, 245, '2021-01-15', N'Əmək Məcəlləsi və Kadr Kargüzarlığı', N'"Business Management School" MMC', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (261, 8410, '2021-09-15', N'Rəsmi mühasibatlıq kursu', N'İATM (İqtisadi araşdırmalar və tədris mərkəzi)', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (301, 10085, '2021-11-24', N'Elektrik avadanlıqlarına xidmət üzrə elektrik montyoru', N'"Azneftkimyamaş-BMZ" ASC Personalın sertifikatlaşdırılması üzrə Təlim Mərkəzi', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (321, 10150, '2021-08-19', N'Cinayət mühakiməsinin psixologiyası', N'Queensland Universiteti', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (322, 10150, '2014-05-15', N'Cənubi Qafqazda regional siyasət və beynəlxalq münasibətlər', N'Vistula Universiteti', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (381, 645, '2001-02-13', N'Hesablama metodu ilə uçot qaydaları', N'Bank Tədris Mərkəzi', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (382, 645, '2001-01-18', N'Qeyri-maddi vəsaitlər', N'Bank Tədris Mərkəzi', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (403, 10516, '2015-05-30', N'School of Business and Finance', N'Barattson', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (542, 11039, '2018-01-07', N'Əmək Məcəlləsi və Kadr Kargüzarlığının Praktiki Təlimi', N'BMS', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (544, 11039, '2017-12-08', N'HR Summit Baku 2017', N'HR Summit Baku 2017', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (561, 11073, '2013-08-01', N'Microsoft Office', N'İdeal hazırlıq kursları', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (621, 11251, '2015-07-16', N'Windows MS Word, MS Excel, Internet Explorer Power Point', N'"Tərəqqi LTD Tədris Mərkəzi" MMC', '2015-07-09');
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (683, 10971, '2018-04-21', N'"İOSH managing safely course"', N'TCS', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (684, 10971, '2018-02-17', N'COSH-Sağlamlıq üçün təhlükəli maddələrin idarə edilməsi', N'TCS', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (685, 10971, '2017-12-16', N'Xilasetmə metodları', N'TCS', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (686, 10971, '2018-01-20', N'Radiasiya təhlükəsizliyi', N'TCS', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (742, 11594, '2020-09-30', N'Döyüş və ictimai-siyasi hazırlıqda fərqləndiyinə görə fəxri Fərman', N'nan', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (688, 10971, '2018-11-10', N'Təhlükəsizlik qurğuları', N'TCS', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (689, 10971, '2018-02-03', N'Əllə görülən işlər', N'TCS', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (821, 12348, '2010-01-06', N'Kompyuter kursu', N'AR Azərbaycan Dəmir Yolçularının Müstəqil Həmkarlar İttifaqı Respublikası Komitəsi  İmişli st.Ə.Həmidov adına Dəmiryol Klubu', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (841, 6882, '2023-09-06', N'Elektrik avadanlıqlarına xidmət üzrə elektrik montyoru', N'"Azneftkimyamaş-BMZ"QSC Personalın sertifikatlaşdırılması üzrə Təlim Mərkəzi', '2026-09-06');
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (962, 13031, '2023-05-18', N'Sertifikat№SO-2234-23', N'AR Rəqəmsal İnkişaf və Nəqliyyat Nazirliyi Dövlət Dəniz və Liman Agentliyi ', '2028-05-12');
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (981, 13153, '2023-11-15', N'Azneftkimyamaş-BMZ', N'	Elektrik avadanlıqlarına xidmət üzrə elektrik montyoru', '2026-11-15');
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (1061, 7029, '2024-06-01', N'Təchizat zəncirinin idarə edilməsi', N'Busniess Management School', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (1081, 13619, '2023-05-15', N'Komando başlanğıc kursu', N'"Komando" Dağ Təlim Mərkəzi', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (1082, 13619, '2022-05-16', N'Gizirlərin Zabit Vəzifələrinə Hazırlığı Kursu', N'AR MN Quru Qoşunları', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (241, 856, '2021-05-18', N'THE NATİONAL İNSTİTUTE FOR ENTREPRENEURSHİP AND SMALL BUSİNESS DEVELOPMENT', N'Ministry of Skill Development and Entrepreneurship, Govt.of İndia ', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (281, 6093, '2019-08-25', N'NEBOSH İGC(SƏTƏMM)', N'GRBS', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (743, 11493, '2014-08-01', N'Achieved a a Distinction with Commendation in the Level 4 Diploma in accounting to International Standartds', N'IAB', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (801, 10971, '2023-07-12', N'İnternal auditor training course (İSO 9001, 45001, 14001)', N'QCS', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (881, 12759, '2017-04-07', N'Komputer proqramları üzrə operator', N'"İdeal" MMC', '2017-07-12');
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (901, 12839, '2015-05-15', N'Kadr Hazırlığı (Qaz paylayıcı stansiyanın operatoru)', N'Təlim, Tədris və sertifikatlaşdırma idarəsi (SOCAR)', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (941, 12986, '2018-06-15', N'Veb layihələrin yaradılması və dizaynı', N'STEP Kompüter Akademiyası', '2018-06-15');
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (963, 13031, '2023-02-22', N'Sertifikat№62615750220223643164', N'RelyOn Nutec Azerbaijan', '2027-02-21');
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (964, 13031, '2021-04-09', N'Sertifikat№AZF-154', N'AZFEN', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (965, 13031, '2015-08-26', N'Sertifikat№AZF-163', N'nan', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (1042, 1645, '2023-12-23', N'Müvəffəqiyyət Sertifikatı (Mühasibat uçotu vergi dərsləri)', N'Turan Tədris Mərkəzi', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (341, 8810, '2021-05-13', N'İnsan Resurslarının İdarə Edilməsi', N'Business Management School MMC', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (361, 10418, '2014-10-01', N'STmark marketing and consulting', N'STmark marketing and consulting', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (383, 645, '2013-01-01', N'Beynəlxalq maliyyə hesabatları üzrə diplom', N'ACCA', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (421, 4625, '2005-04-18', N'Kreditlərin idarə edilməsi', N'Azərbaycan Bank Tədris Mərkəzi', '2005-04-22');
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (422, 4625, '2005-07-19', N'təsirin qiymətləndirilməsinə və bazar araşdırmasına giriş', N'Mikromaliyyə mərkəzi', '2005-07-22');
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (441, 1175, '2009-02-08', N'Şəhdətnamə, İnformatiknın əsasları ', N'Naxçıvan Muxtar Respublikası kompyuter təlim-tədris və internet mərkəzi', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (481, 10411, '2022-06-26', N'THE İnternational financial accounting and 1C 8.3"', N'EDU Company', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (501, 10971, '2020-04-03', N'Praktiki Mühasibatlıq', N'AzFin', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (502, 10971, '2020-09-26', N'Confined Space', N'TCS', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (503, 10971, '2020-09-19', N'Plant İnspection', N'TCS', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (521, 11000, '2007-09-25', N'Komputer kursu', N'"Baku Business University" training courses', '2007-12-25');
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (541, 11039, '2018-09-28', N'Training on İnternational İSO9001:2015,İSO 14001:2015 and İSO 45001:2018 İntegrated Management Systems', N'MEYER LLC', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (543, 11039, '2019-12-07', N'Məşğulluq Hesabatları və Elektron İnformasiya Sistemində İşləmə Qaydaları', N'Fire Works HRM', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (545, 11051, '2015-04-25', N'komputer kursu', N'MAGİC LANGUAGES', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (562, 10613, '2021-04-25', N'Müasir şəraitdə həmkarlar ittifaqı təşkilatının fəaliyyətinin əsas istiqamətləri', N'Azərbaycan Əmək və Sosial münasibətlər Akademiyası', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (563, 10893, '2016-11-14', N'ISO9001:2015,İSO14001:2015,OHSAS18001:2007', N'"TCS" LLC', '2016-11-17');
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (761, 11896, '2023-04-26', N'Təchizat zənciri', N'Business Management School', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (782, 11039, '2015-04-01', N'Fəxri Fərman', N'Azərbaycan Respublikası İnşaat İş Həmkarlar İttifaqı', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (783, 11039, '2019-04-09', N'Fəxri Fərman', N'Azərbaycan Həmkarlar İttifaqları Konfederasiyası', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (784, 11039, '2017-11-26', N'Əmək Məcəlləsi və Kadr Kargüzarlığının Praktiki Təlimi', N'BMS', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (921, 12967, '2021-03-01', N'Windows, Microsoft Office (Word, Excel, PowerPoint), Internet Explorer proqramlarında təcrübə əldə etmişdir', N'Azərbaycan Respublikası Uşaq və Tələbə Gənclər Dünyası İ.B. "Gənclər və Mədəniyyət evi) Tədris Mərkəzi', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (961, 13031, '2014-07-01', N'Sertifikat№EM-017', N'Azərkimyamaş ASC Təlim mərkəzi', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (1001, 11039, '2024-04-02', N'Human Resources Management ', N'İnternational Education Research Certificate Center', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (121, 221, '2019-06-26', N'DAT201x: Querying Data with Transact-SQL', N'eDX', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (81, 221, '2019-04-12', N'DAT249x: Ethics and Law in Data and Analytics', N'edX', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (101, 221, '2019-05-17', N'DAT207x: Analyzing and Visualizing Data with Power BI', N'eDX', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (141, 6771, '2018-12-25', N'Financial Reporting (FR)', N'ACCA', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (41, 221, '2016-07-01', N'M101J: MongoDB for Java Developers', N'MongoDB İnc.', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (21, 6771, '2018-08-25', N'Financial Accounting (FA)                                                                 ', N'ACCA', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (22, 6771, '2019-01-01', N' Diploma in İnternational Financial Reporting', N'ACCA', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (42, 221, '2015-07-11', N'Java SE EE', N'Orient İTM', '2016-07-11');
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (61, 221, '2019-03-22', N' DAT101x: Introduction to Data Science ', N'edX', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (62, 221, '2018-06-21', N'Cisco Certified Network Associate Routing and Switching', N'Cisco Systems Inc.', '2021-06-21');
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (581, 1588, '2018-06-26', N'Elektrik montyoru', N'"Profil-Resurs" Peşə Tədris Mərkəzi', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (681, 10971, '2018-11-29', N'İSO 9001:2015, 45001:2018, 14001:2015, İnternal Audit', N'TCS', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (785, 7029, '2023-07-11', N'Certificate of Attendance', N'Quality Consulting Services LLC', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (1021, 11039, '2024-06-04', N'Human Resources Management', N'İEE Center', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (1041, 10971, '2018-06-01', N'Əməyin mühafizəsi üzrə yerli qanunvericiliyin tələbləri', N'"Gİ" training academy', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (161, 8835, '2019-01-12', N'İ.S.S. Tədris', N'İ.S.S Tədris Mərkəzi', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (181, 9220, '2014-07-25', N'Mühafizəçilərin ixtisaslaşdırılmış tədris mərkəzi', N'Mühafizəçilərin ixtisaslaşdırılmış tədris mərkəzi', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (201, 245, '2020-12-19', N'"İnsan resurslarının idarə edilməsi" təlimi', N'"Business Management School" MMC', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (202, 8810, '2021-01-15', N'Əmək Məcəlləsi və Kadr Kargüzarlığı', N'Business Management School MMC', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (282, 6093, '2020-07-27', N'İSO(9001,14001,45001)', N'ZEYN Consulting', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (401, 10516, '2014-07-18', N'"Successful Strategies"', N'"Yeni korporativ müştərilərə bank məhsullarınıın  aktiv satışı" treninqində iştirak etmişdir.', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (402, 10516, '2012-05-16', N'AR Bank Tədris Mərkəzi', N'Aktiv/Passivlərinin idarə edilməsi. Xəzinədarlıq', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (461, 426, '2019-09-22', N'Diplom-Kəndirdartma növündə 2-ci yer tutduğuna görə', N'"Neftçi idman klubu "', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (601, 11224, '2013-03-04', N'Nəzarət ölçü cihazları və avtomatika üzrə çilingər', N'ARDNŞ Təlim və Sertifikatlaşdırma İdarəsi', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (641, 11425, '2018-01-30', N'Mülki müdafiə qüvvələrinin "Komandir-rəis heyəti"', N'Təlim, Tədris və Sertifikatlaşdırma İdarəsi', '2018-02-01');
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (642, 11425, '2016-05-02', N'"SOCAR-ın Ekoloji siyasəti"', N'Təlim, Tədris və Sertifikatlaşdırma İdarəsi', '2016-05-06');
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (643, 11425, '2016-01-19', N'"Komandir-rəis heyəti"', N'Təlim, Tədris və Sertifikatlaşdırma İdarəsi', '2016-01-22');
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (644, 11425, '2015-05-25', N'"Qəza-xilasetmə qrupu"', N'Təlim, Tədris və Sertifikatlaşdırma İdarəsi', '2015-05-27');
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (645, 11425, '2014-07-02', N'"Yanğın texniki minimumu"', N'Təlim, Tədris və Sertifikatlaşdırma İdarəsi', '2014-07-04');
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (646, 11425, '2014-02-03', N'"Tullantıların idarə olunması"', N'Təlim, Tədris və Sertifikatlaşdırma İdarəsi', '2014-02-07');
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (647, 11427, '2007-04-07', N'Peşəkar maliyyə meneceri', N'Beynəlxalq mühasib standartları', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (648, 11427, '2007-06-21', N'Peşəkar maliyyə meneceri	', N'Maliyyə menecmenti', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (649, 11427, '2007-09-01', N'Peşəkar maliyyə meneceri	', N'Beynəlxalq maliyyə standartları', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (661, 11434, '2010-12-01', N'Accounting and Advanced book-keeping', N'İAB', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (682, 10971, '2019-11-29', N'Risklərin qiymətləndirilməsi', N'"Gİ" consulting group', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (701, 11493, '2015-06-06', N'Beynəlxəlq Maliyyə Hesabatları Standartları üzrə diplom ', N'apfm', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (702, 11493, '2013-08-23', N'İnternational financial reporting standards', N'The İnstitute of Certified Financial Managers', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (703, 11493, '2012-08-07', N'Achieved a Credit in the Level 3 Diploma in accounting and advanced book-keeping', N'İAB', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (721, 11434, '2011-09-16', N'İnternational financial reporting standards', N'The İnstitute of Certified Financial Managers', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (741, 11594, '2016-10-11', N'Sertifikat', N'Azərbaycan Respublikası Prezident yanında Gənclər Fondu', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (781, 11039, '2017-12-23', N'İnsan resurslarının idarəedilməsi', N'Vətənpərvər Maarifçi Gənclər İctimai Birliyi', NULL);
INSERT INTO Certificates (Id, EmployeeId, GivenAt, Name, Organization, ValidUntil) VALUES (861, 8810, '2024-04-24', N'HR Audit və Qanunvericilik', N'Barattson LLC', NULL);

