INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (323, 5, N'İzmir');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (243, 1, N'Şimal rayonları');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (283, 1, N'Lerik');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (303, 1, N'Şuşa');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (404, 1, N'Göyçay');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (483, 1, N'Saatlı');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (544, 1, N'Cəbrayıl');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (545, 1, N'Zəngilan');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (546, 1, N'Kəlbəcər');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (563, 1, N'Ağdaş');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (603, 1, N'Tərtər');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (604, 1, N'Xocalı');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (623, 1, N'Ağdərə');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (643, 1, N'Naftalan');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (263, 1, N'Zərdab ');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (363, 1, N'Ağdam');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (463, 1, N'Mingəçevir');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (523, 1, N'İsmayıllı rayonu');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (543, 1, N'Füzuli ');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (122, 81, N'Dubay');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (14, 5, N'Ankara');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (22, 1, N'Qazax');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (23, 1, N'Şirvan');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (24, 1, N'Sabirabad');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (25, 1, N'Ucar');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (26, 1, N'Bərdə');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (27, 1, N'Zaqatala');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (28, 1, N'Şəki');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (29, 1, N'Xaçmaz');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (30, 1, N'Lənkəran');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (31, 1, N'Yevlax');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (32, 1, N'Kürdəmir');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (33, 1, N'Ləki');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (34, 1, N'Goranboy');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (35, 1, N'Şəmkir');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (36, 1, N'Ağstafa');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (37, 1, N'Ağcabədi');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (38, 1, N'Tovuz-Qovlar');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (42, 1, N'Masallı ');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (43, 1, N'Cəlilabad');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (62, 21, N'Yokohama');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (102, 61, N'Milan');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (144, 1, N'Horadiz');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (145, 1, N'Beyləqan');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (162, 1, N'Fəaliyyət göstərməyən NTB-lər');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (182, 1, N'Siyəzən ');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (202, 1, N'Şamaxı ');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (222, 61, N'Reggio Emilio');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (242, 1, N'Hacıqabul');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (8, 1, N'Quba');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (9, 2, N'Rostov');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (1, 1, N'Bakı');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (2, 1, N'Sumqayıt');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (4, 2, N'Moskva');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (5, 1, N'Gəncə');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (6, 3, N'Tiflis');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (82, 41, N'Tehran');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (13, 5, N'İstanbul');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (44, 1, N'Salyan');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (143, 61, N'Parma');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (183, 1, N'Pirallahı');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (383, 1, N'Xocavənd');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (423, 121, N'Buxarest');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (343, 1, N'Qubadlı');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (403, 1, N'Laçın');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (443, 1, N'Naxçıvan ');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (503, 1, N'Qusar');
INSERT INTO Cities ([Id], [CountryId], [Name]) VALUES (583, 1, N'Xankəndi');