
--THESE Employees are not added:

INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (9964, 13706, 20, 1996, N'Hədiyyə', N'Talıbova', N'Hacıhəsən');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (9965, 13706, 30, 2023, N'Aras', N'Talıbzadə', N'Orxan');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (9966, 13702, 20, 2004, N'Aygün', N'Süleymanova', N'A');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (9967, 13703, 20, 1963, N'Səmbər', N'Ağayeva', N'A');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (9968, 13703, 40, 1990, N'Gülüş', N'Ağayeva', N'Mahir');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (9969, 13703, 40, 1991, N'Günel', N'Abuşova', N'Mahir');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (9970, 13709, 10, 1965, N'İlham', N'İsayev', N'Həsən');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (9971, 13709, 40, 1990, N'Nigar', N'Məmmədli', N'İlham');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (9972, 13709, 40, 1992, N'Nərmin', N'Muradova', N'İlham');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (9973, 13708, 20, 1998, N'Feyzə', N'İsayeva', N'İlkin');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (9974, 13707, 40, 2007, N'Xadicə', N'Ələkbərova', N'Rəcəb');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (9975, 13714, 20, 1970, N'Xalidə', N'Əhmədova', N'İbiş');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (9976, 13714, 30, 1992, N'Kənan', N'Əhmədov', N'Novruz');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (9977, 13714, 30, 1994, N'Sənan', N'Əhmədov', N'Novruz');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (9978, 13720, 20, 2003, N'Günay', N'Hacoğlanova', N'A');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (9979, 13718, 10, 1970, N'Afət', N'Quliyev', N'Ramazan');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (9980, 13718, 30, 1992, N'Asəf', N'Quliyev', N'Afət');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (9981, 13718, 30, 1994, N'Azər', N'Quliyev', N'Afət');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (9982, 13718, 40, 1999, N'Mənsurə', N'Quliyeva', N'Afət');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (10002, 13736, 20, 1976, N'Tünzalə', N'Həşimova', N'Nəsib');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (10003, 13736, 30, 2001, N'Azay', N'Həşimov', N'Əhməd');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (10004, 13736, 40, 2003, N'Jalə', N'Həşimova', N'Əhməd');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (10005, 13746, 20, 1988, N'Ülviyyə', N'Cəbrayılova', N'Ərzuman');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (10006, 13745, 20, 1994, N'İlahə', N'Cəbiyeva', N'İlqar');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (10007, 13745, 40, 2013, N'Ləman', N'Cəbizadə', N'Kamran');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (10008, 13745, 30, 2014, N'Hüseyn', N'Cəbizadə', N'Kamran');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (10009, 13745, 30, 2022, N'Üzeyir', N'Cəbizadə', N'Kamran');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (10010, 13747, 20, 2003, N'Bəxtinisə', N'Qurbanova', N'Ceyhun');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (10011, 13735, 20, 1981, N'Aynur', N'Qasımova', N'Fəzail');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (10012, 13735, 40, 2019, N'Ayan', N'Qasımlı', N'Rafael');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (10013, 13735, 40, 2009, N'Nuray', N'Qasımlı', N'Rafael');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (10014, 13735, 30, 2012, N'Nurlan', N'Qasımlı', N'Rafael');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (10022, 13776, 20, 1993, N'Heyran', N'Mövləmova', N'Teymur');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (10023, 13776, 40, 2020, N'Mələk', N'Mövləmli', N'Kamran');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (10024, 13776, 40, 2022, N'Dilək', N'Mövləmli', N'Kamran');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (10025, 10977, 30, 2023, N'Nihad', N'Hüseynzadə', N'Kamran');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (10026, 13756, 20, 1988, N'Rühəngiz', N'Bələdova', N'A');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (10027, 13756, 30, 2018, N'Uğur', N'Bədəlli', N'Samir');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (10028, 13756, 40, 2015, N'Aysun', N'Bədəlli', N'Samir');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (10029, 13777, 50, 1947, N'Fariz', N'Quliyev', N'Əzizağa');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (10030, 13777, 60, 1948, N'Zinaida', N'Quliyeva', N'Cəlil');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (10031, 13778, 20, 1995, N'Nurhalə ', N'Ağayeva', N'Ərrəhman');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (10032, 13778, 30, 2011, N'Elgün', N'Ağayev', N'Elşad');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (10033, 13778, 30, 2012, N'Əli ', N'Ağayev', N'Elşad');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (10034, 13782, 20, 2006, N'Çiçək', N'Məmmədova', N'Qulu');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (10035, 13782, 40, 2024, N'Nəzrin', N'Məmmədova', N'Coşqun');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (10036, 13785, 20, 2004, N'Minarə ', N'Hüseynzadə ', N'Rəşad');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (10042, 13786, 50, 1965, N'Asim', N'Əsədullayev', N'Yusif');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (10043, 13786, 60, 1971, N'Tamilla', N'Əliyeva', N'Əliağa');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (10044, 13786, 40, 2020, N'Nirsa', N'Əsədullayeva', N'Fərid');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (10045, 13794, 20, 1997, N'Günay', N'Məmmədli ', N'Firudin');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (10046, 13794, 30, 2018, N'Tunar', N'Məmmədli', N'Hüseyn');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (10047, 13794, 40, 2016, N'Zəhra', N'Məmmədli', N'Hüseyn');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (10048, 13795, 50, 1973, N'Şamil', N'Məmmədov ', N'Natiq');
INSERT INTO FamilyMembers (Id, EmployeeId, FamilyMemberTypeId, BirthYear, Name, Surname, FatherName) VALUES (10049, 13795, 60, 1978, N'Ruhəngiz ', N'Kərimova', N'Məmmədrza');