INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2012-01-01', N'Yeni İl', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2012-02-01', N'Yeni İl', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2012-03-01', N'Yeni il', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2012-01-20', N'20 Yanvar', 2, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2012-08-03', N'8 Mart Beynəlxalq Qadınlar günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2012-03-20', N'Novruz Bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2012-03-21', N'Novruz Bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2012-03-22', N'Novruz Bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2012-03-23', N'Novruz Bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2012-03-24', N'Novruz Bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2012-03-25', N'Novruz Bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2012-09-05', N'Qələbə günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2012-05-28', N'Respublika günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2012-06-15', N'Milli Qurtuluş Günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2012-06-26', N'Silahlı Qüvvələr Günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2012-08-20', N'Ramazan Bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2012-08-21', N'Ramazan Bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2012-10-25', N'Qurban Bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2012-10-26', N'Qurban Bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2012-09-11', N'Dövlət bayrağı günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2012-12-31', N'Dünya Azərbaycanlılarının Həmrəyliyi günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2013-01-01', N'Yeni il', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2013-02-01', N'Yeni il', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2013-01-20', N'Ümumxalq hüzn günü', 2, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2013-08-03', N'Qadınlar günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2013-03-20', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2013-03-21', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2013-03-22', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2013-03-23', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2013-03-24', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2013-09-05', N'Faşizm üzərində qələbə günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2013-05-28', N'Respublika günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2013-06-15', N'Milli qurtuluş günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2013-06-26', N'Silahlı qüvvələr günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2013-08-08', N'Ramazan bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2013-09-08', N'Ramazan bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2013-09-10', N'AR Prezident seçkiləri günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2013-10-15', N'Qurban bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2013-10-16', N'Qurban bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2013-09-11', N'AR Dövlət bayrağı günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2013-12-31', N'Dünya azərbaycanlılarının həmrəyliyi günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2014-01-01', N'Yeni il', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2014-02-01', N'Yeni il', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2014-01-20', N'Ümumxalq hüzn günü', 2, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2014-08-03', N'Qadınlar günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2014-03-20', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2014-03-21', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2014-03-22', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2014-03-23', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2014-03-24', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2014-09-05', N'Faşizm üzərində qələbə günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2014-05-28', N'Respublika günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2014-06-15', N'Azərbaycan xalqının milli qurtuluş günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2014-06-26', N'AR Silahlı Qüvvələri günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2014-07-28', N'Ramazan bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2014-07-29', N'Ramazan bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2014-04-10', N'Qurban bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2014-05-10', N'Qurban bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2014-06-10', N'Qurban Bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2014-07-10', N'Qurban bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2014-09-11', N'AR Dövlət Bayrağı günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2014-12-31', N'Dünya azərbaycanlılarının həmrəyliyi günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2015-01-01', N'Yeni il', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2015-02-01', N'Yeni il', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2015-01-20', N'Ümumxalq hüzn günü', 2, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2015-08-03', N'Qadınlar günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2015-03-20', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2015-03-21', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2015-03-22', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2015-03-23', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2015-03-24', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2015-09-05', N'Faşizm üzərində qələbə günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2015-05-28', N'Respublika günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2015-06-15', N'Azərbaycan xalqının milli qurtuluş günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2015-06-26', N'AR Silahlı Qüvvələri günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2015-07-17', N'Ramazan bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2015-07-18', N'Ramazan bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2015-09-24', N'Qurban bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2015-09-25', N'Qurban bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2015-09-11', N'AR Dövlət Bayrağı günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2015-12-31', N'Dünya azərbaycanlılarının həmrəyliyi günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2016-09-11', N'Azərbaycan Respublikasının Dövlət Bayrağı günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2016-12-31', N'Dünya Azərbaycanlılarının həmrəyliyi günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2017-01-01', N'Yeni il bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2017-02-01', N'Yeni il bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2017-03-01', N'Yeni il bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2017-04-01', N'Yeni il bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2017-01-20', N' Ümumxalq hüzn günü', 2, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2017-08-03', N'Qadınlar günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2017-03-20', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2017-03-21', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2017-03-22', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2017-03-23', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2017-03-24', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2017-09-05', N'Faşizm üzərində qələbə günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2017-05-28', N'Respublika günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2017-05-29', NULL, 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2017-06-15', N'Qurtuluş günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2017-06-26', N'Silahlı qüvvələr günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2017-06-27', N'Ramazan bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2017-06-28', NULL, 3, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2017-01-09', N'Qurban bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2017-02-09', N'Qurban bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2017-04-09', N'Ramazan bayrami', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2017-09-11', N'Dövlət bayrağı günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2017-12-31', N'Dünya Azərbaycanlılarının həmrəyliyi günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2018-01-01', N'Yeni il  bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2018-02-01', N'Yeni il  bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2018-03-01', N'Yeni il  bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2018-01-20', NULL, 2, 2);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2018-08-03', N'Qadınlar günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2018-03-20', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2018-03-21', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2018-03-22', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2018-03-23', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2018-03-23', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2018-03-24', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2018-03-26', N'Novruz bayramı', 1, 1);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2018-11-04', N'Prezident seçkiləri', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2018-09-05', N'Qələbə günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2018-05-28', N'Respublika günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2018-06-15', NULL, 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2018-06-16', N'Ramazan bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2018-06-17', NULL, 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2018-06-18', NULL, 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2018-06-19', NULL, 1, 1);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2018-06-26', N'Azərbaycan Respublikasının Silahlı Qüvvələri günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2018-08-22', N'Qurban Bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2018-08-23', N'Qurban Bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2018-09-11', N'Azərbaycan Respublikasının Dövlət bayrağı günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2018-12-31', N'Dünya Azərbaycanlılarının həmrəyliyi günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2019-01-01', N'Yeni il', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2019-02-01', N'Yeni il', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2019-01-20', N'Ümümxalq hüzn günü', 2, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2019-08-03', N'8 mart qadınlar bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2019-03-20', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2019-03-21', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2019-03-22', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2019-03-23', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2019-03-24', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2019-03-25', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2019-03-26', N'Novruz bayramı', 1, 1);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2019-09-05', N'Faşizm üzərində qələbə günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2019-05-28', N'Respublika günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2019-05-06', N'Ramazan bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2019-06-06', N'Ramazan bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2019-06-15', N'Azərbaycan xalqının milli qurtuluş günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2019-06-17', NULL, 1, 1);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2019-06-26', N'Azərbaycan Respublikasının Silahlı Qüvvələri günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2019-12-08', N'Qurban Bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2019-08-13', N'Qurban Bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2019-09-11', N'Azərbaycan Respublikasının Dövlət bayrağı günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2019-11-11', NULL, 3, 1);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2019-12-31', N'Dünya Azərbaycanlılarının həmrəyliyi günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2020-01-01', N'Yeni il bayramı', 1, 2);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2020-02-01', N'Yeni il bayramı', 1, 3);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2020-03-01', N'Yeni il bayramı', 1, 1);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2020-01-20', N'Ümumxalq Hüzn günü', 2, 2);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2020-08-03', N'Qadınlar günü', 1, 2);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2020-03-20', N'Novruz bayramı', 1, 2);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2020-03-21', N'Novruz bayramı', 1, 2);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2020-03-22', N'Novruz bayramı', 1, 2);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2020-03-23', N'Novruz bayramı', 1, 2);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2020-03-24', N'Novruz bayramı', 1, 2);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2020-03-25', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2020-03-26', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2020-09-05', N'Faşizm üzərində Qələbə günü', 1, 2);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2020-05-23', NULL, 3, 1);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2020-05-24', N'Ramazan  bayramı', 1, 2);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2020-05-25', N'Ramazan  bayramı', 1, 2);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2020-05-27', NULL, 3, 2);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2020-05-28', N'Respublika günü', 1, 2);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2020-05-29', NULL, 4, 2);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2020-05-30', NULL, 3, 1);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2020-05-30', NULL, 4, 3);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2020-06-15', N'Azərbaycan xalqının Milli Qurtuluş  günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2020-06-26', N'Silahlı qüvvələr günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2020-06-26', N'Silahlı qüvvələr günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2020-07-31', N'Qurban bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2020-01-08', N'Qurban bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2020-02-08', NULL, 1, 4);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2020-03-08', NULL, 3, 1);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2020-09-11', N'Azərbaycan Respublikasının Dövlət Bayrağı günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2020-12-31', N'Dünya Azərbaycanlılarının  Həmrəyliyi günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2021-01-01', N'Yeni il bayramı ', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2021-02-01', N'Yeni il bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2021-03-01', NULL, 3, 4);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2021-04-01', NULL, 3, 1);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2021-01-20', N'Ümumxalq Hüzn günü', 2, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2021-08-03', N'Qadınlar günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2021-03-20', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2021-03-21', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2021-03-22', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2021-03-23', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2021-03-24', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2021-03-25', NULL, 3, 2);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2021-03-26', NULL, 3, 1);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2021-08-05', NULL, 5, 1);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2021-09-05', N'Faşizm üzərində Qələbə günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2021-10-05', NULL, 3, 5);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2021-11-05', NULL, 3, 2);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2021-12-05', NULL, 3, 2);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2021-05-13', N'Ramazan  bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2021-05-14', N'Ramazan  bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2021-05-16', NULL, 5, 2);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2021-05-28', N'Müstəqillik günü ', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2021-05-28', N'Respublika günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2021-06-15', N'Azərbaycan xalqının Milli Qurtuluş  günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2021-06-26', N'Azərbaycan Respublikasının Silahlı Qüvvələri  günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2021-06-28', NULL, 3, 1);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2021-12-07', N'İstirahət günü ', 3, 1);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2021-07-17', NULL, 5, 1);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2021-07-19', NULL, 3, 1);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2021-07-20', N'Qurban bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2021-07-21', N'Qurban bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2021-08-11', N'Zəfər günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2021-09-11', N'Azərbaycan Respublikasının Dövlət Bayrağı günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2021-12-31', N'Dünya Azərbaycanlılarının  Həmrəyliyi günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2022-01-01', N'Yeni il bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2022-02-01', N'Yeni il bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2022-03-01', N'İstirahət günü', 3, 2);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2022-04-01', N'İstirahət günü ', 3, 1);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2022-01-20', N'Ümumxalq hüzn günü ', 2, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2022-05-03', NULL, 5, 1);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2022-07-03', NULL, 3, 1);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2022-08-03', N'Qadınlar günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2022-03-20', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2022-03-21', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2022-03-22', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2022-03-23', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2022-03-24', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2022-03-25', N'İstirahət günü ', 3, 5);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2022-02-05', N'Ramazan  bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2022-03-05', N'Ramazan  bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2022-09-05', N'Faşizm üzərində Qələbə günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2022-05-28', N'Müstəqillik günü ', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2022-05-29', NULL, 3, 4);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2022-05-30', N'İstirahət günü ', 3, 1);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2022-06-15', N'Azərbaycan xalqının milli qurtuluş  günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2022-06-26', N'Azərbaycan Respublikasının Silahlı Qüvvələri  günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2022-06-27', N'İstirahət günü ', 3, 5);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2022-09-07', N'Qurban bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2022-10-07', N'Qurban bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2022-11-07', N'İstirahət günü ', 3, 2);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2022-12-07', N'İstirahət günü ', 3, 1);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2022-05-11', NULL, 5, 1);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2022-07-11', NULL, 3, 1);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2022-08-11', N'Zəfər günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2022-09-11', N'Azərbaycan Respublikasının Dövlət Bayrağı günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2022-12-31', N'Dünya Azərbaycanlılarının  Həmrəyliyi günü', 1, NULL);



INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2023-01-01', N'Yeni il bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2023-02-01', N'Yeni il bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2023-03-01', NULL, 3, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2023-04-01', NULL, 3, 1);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2023-01-20', N'Ümumxalq hüzn günü', 2, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2023-08-03', NULL, 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2023-03-20', NULL, 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2023-03-21', NULL, 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2023-03-22', NULL, 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2023-03-23', NULL, 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2023-03-24', NULL, 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2023-04-21', NULL, 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2023-04-22', NULL, 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2023-04-23', NULL, 3, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2023-04-24', NULL, 3, 1);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2023-09-05', NULL, 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2023-05-28', NULL, 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2023-05-29', NULL, 3, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2023-06-15', NULL, 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2023-06-24', NULL, 5, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2023-06-25', NULL, 5, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2023-06-26', NULL, 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2023-06-27', NULL, 1, 1);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2023-06-28', NULL, 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2023-06-29', NULL, 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2023-06-30', NULL, 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2023-01-07', NULL, 1, 1);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2023-04-11', NULL, 5, 1);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2023-08-11', NULL, 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2023-09-11', NULL, 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2023-10-11', NULL, 3, 1);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2023-12-31', NULL, 1, NULL);













INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2024-01-01', NULL, 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2024-01-02', NULL, 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2024-01-03', NULL, 3, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2024-01-04', NULL, 3, 1);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2024-01-05', NULL, 3, 1);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2024-01-06', NULL, 3, 1);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2024-01-07', NULL, 5, 1);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2024-01-20', N'Ümumxalq hüzn günü', 2, NULL);


INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2024-02-07', N'Azərbaycan Respublikası Prezidenti seçkiləri günü', 1, NULL);

INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2024-03-08', N'Qadınlar günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2024-03-20', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2024-03-21', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2024-03-22', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2024-03-23', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2024-03-24', N'Novruz bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2024-03-25', NULL, 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2024-03-26', NULL, 3, 1);


INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2024-04-06', NULL, 5, 1);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2024-04-10', N'Ramazan  bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2024-04-11', N'Ramazan  bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2024-04-12', NULL, 3, 1);


INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2024-05-09', N'Faşizm üzərində qələbə günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2024-05-28', N'Müstəqillik Günü', 1, NULL);


INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2024-06-15', N'Azərbaycan xalqının milli qurtuluş günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2024-06-16', N'Qurban bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2024-06-17', N'Qurban bayramı', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2024-06-18', NULL, 3, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2024-06-19', NULL, 3, 1);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2024-06-26', N'Azərbaycan Respublikasının Silahlı Qüvvələri  günü', 1, NULL);


INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2024-09-01', N'Azərbaycan Respublikası Parlament seçkiləri günü', 1, 3);

INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2024-11-08', N'Zəfər Günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2024-11-09', N'Azərbaycan Respublikasının Dövlət bayrağı günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2024-11-11', NULL, 3, 1);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2024-11-12', NULL, 3, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2024-11-13', NULL, 3, NULL);

INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2024-11-16', N'12.11.2024 əvəzi', 5, 1);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2024-11-23', N'13.11.2024 əvəzi', 5, 1);


INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2024-12-23', N'Bələdiyyə seçkiləri günü', 1, NULL);
INSERT INTO Holidays (Date, Note, HolidayTypeId, HolidayForShiftId) VALUES ('2024-12-31', N'Dünya azərbaycanlılarının həmrəyliyi günü', 1, NULL);

