INSERT INTO MedalTypes (Id, Type) VALUES (100, N'"Heydər Əliyev" ordeni');
INSERT INTO MedalTypes (Id, Type) VALUES (200, N'"İstiqlal" ordeni');
INSERT INTO MedalTypes (Id, Type) VALUES (300, N'"Şah İsmayıl" ordeni');
INSERT INTO MedalTypes (Id, Type) VALUES (400, N'"Azərbaycan Bayrağı" ordeni');
INSERT INTO MedalTypes (Id, Type) VALUES (500, N'"Şərəf" ordeni');
INSERT INTO MedalTypes (Id, Type) VALUES (600, N'"Şöhrət" ordeni');
INSERT INTO MedalTypes (Id, Type) VALUES (700, N'"Dostluq" ordeni');
INSERT INTO MedalTypes (Id, Type) VALUES (800, N'"Vətənə xidmətə görə" ordeni I dərəcəli');
INSERT INTO MedalTypes (Id, Type) VALUES (810, N'"Vətənə xidmətə görə" ordeni II dərəcəli');
INSERT INTO MedalTypes (Id, Type) VALUES (820, N'"Vətənə xidmətə görə" ordeni III dərəcəli');
INSERT INTO MedalTypes (Id, Type) VALUES (900, N'"Əmək" ordeni I dərəcəli');
INSERT INTO MedalTypes (Id, Type) VALUES (910, N'"Əmək" ordeni II dərəcəli');
INSERT INTO MedalTypes (Id, Type) VALUES (920, N'"Əmək" ordeni III dərəcəli');
INSERT INTO MedalTypes (Id, Type) VALUES (10100, N'"Qızıl Ulduz" medalı');
INSERT INTO MedalTypes (Id, Type) VALUES (10200, N'"Vətən uğrunda" medalı');
INSERT INTO MedalTypes (Id, Type) VALUES (10300, N'"İgidliyə görə" medalı');
INSERT INTO MedalTypes (Id, Type) VALUES (10400, N'"Tərəqqi" medalı');
INSERT INTO MedalTypes (Id, Type) VALUES (10500, N'"Hərbi xidmətdə fərqlənməyə görə" medalı');
INSERT INTO MedalTypes (Id, Type) VALUES (10600, N'"Hərbi xidmətlərə görə" medalı');
INSERT INTO MedalTypes (Id, Type) VALUES (10700, N'"Hərbi əməkdaşlıq sahəsində xidmətlərə görə" medalı');
INSERT INTO MedalTypes (Id, Type) VALUES (10800, N'"Azərbaycan Respublikası Silahlı Qüvvələri Veteranı" medalı');
INSERT INTO MedalTypes (Id, Type) VALUES (10900, N'"Qüsursuz xidmətə görə" medalı');
INSERT INTO MedalTypes (Id, Type) VALUES (10910, N'"Qüsursuz xidmətə görə" medalı I dərəcəli');
INSERT INTO MedalTypes (Id, Type) VALUES (10920, N'"Qüsursuz xidmətə görə" medalı II dərəcəli');
INSERT INTO MedalTypes (Id, Type) VALUES (10930, N'"Qüsursuz xidmətə görə" medalı III dərəcəli');
INSERT INTO MedalTypes (Id, Type) VALUES (11000, N'"Dövlət qulluğunda fərqlənməyə görə" medalı');
INSERT INTO MedalTypes (Id, Type) VALUES (11100, N'"Azərbaycan Ordusunun 100 illiyi (1918-2018)" yubiley medalı');
INSERT INTO MedalTypes (Id, Type) VALUES (11110, N'"Milli Ordu - 100" medalı');
INSERT INTO MedalTypes (Id, Type) VALUES (11200, N'"Azərbaycan Respublikası Silahlı Qüvvələrinin 95 illiyi (1918-2013)" yubiley medalı');
INSERT INTO MedalTypes (Id, Type) VALUES (11300, N'"Azərbaycan Respublikası Silahlı Qüvvələrinin 90 illiyi (1918-2008)" yubiley medalı');
INSERT INTO MedalTypes (Id, Type) VALUES (11400, N'"Azərbaycan Respublikası Silahlı Qüvvələrinin 10 illiyi (1991-2001)" yubiley medalı');
INSERT INTO MedalTypes (Id, Type) VALUES (11500, N'"Şücaətə görə" medalı');
INSERT INTO MedalTypes (Id, Type) VALUES (11600, N'"Rəşadət" ordeni I dərəcəli');
INSERT INTO MedalTypes (Id, Type) VALUES (11610, N'"Rəşadət" ordeni II dərəcəli');
INSERT INTO MedalTypes (Id, Type) VALUES (11620, N'"Rəşadət" ordeni III dərəcəli');
INSERT INTO MedalTypes (Id, Type) VALUES (11650, N'"Müharibə veteranı" medalı');
INSERT INTO MedalTypes (Id, Type) VALUES (11700, N'"Vətən müharibəsi iştirakçısı" medalı');
INSERT INTO MedalTypes (Id, Type) VALUES (11800, N'"Vətən müharibəsində arxa cəbhədə xidmətlərə görə" medalı');
INSERT INTO MedalTypes (Id, Type) VALUES (11900, N'"Laçının azad olunmasına görə" medalı');
INSERT INTO MedalTypes (Id, Type) VALUES (12000, N'"Ağdamın azad olunmasına görə" medalı');
INSERT INTO MedalTypes (Id, Type) VALUES (12100, N'"Kəlbəcərin azad olunmasına görə" medalı');
INSERT INTO MedalTypes (Id, Type) VALUES (12200, N'"Şuşanın azad olunmasına görə" medalı');
INSERT INTO MedalTypes (Id, Type) VALUES (12300, N'"Qubadlının azad olunmasına görə" medalı');
INSERT INTO MedalTypes (Id, Type) VALUES (12400, N'"Zəngilanın azad olunmasına görə" medalı');
INSERT INTO MedalTypes (Id, Type) VALUES (12500, N'"Füzulinin azad olunmasına görə" medalı');
INSERT INTO MedalTypes (Id, Type) VALUES (12600, N'"Xocavəndin azad olunmasına görə" medalı');
INSERT INTO MedalTypes (Id, Type) VALUES (12700, N'"Cəbrayılın azad olunmasına görə" medalı');
INSERT INTO MedalTypes (Id, Type) VALUES (12800, N'"Suqovuşanın azad olunmasına görə" medalı');
INSERT INTO MedalTypes (Id, Type) VALUES (12900, N'"Döyüşdə fərqlənməyə görə" medalı');
INSERT INTO MedalTypes (Id, Type) VALUES (13000, N'"Cəsur döyüşçü" medalı');
INSERT INTO MedalTypes (Id, Type) VALUES (13100, N'"Vətən Müharibəsi Qəhrəmanı" Azərbaycan Respublikası medalı');
INSERT INTO MedalTypes (Id, Type) VALUES (13200, N'"Qarabağ" ordeni');
INSERT INTO MedalTypes (Id, Type) VALUES (13300, N'"Zəfər" ordeni');
INSERT INTO MedalTypes (Id, Type) VALUES (13400, N'"Qarabağ Uğrunda" medalı');
INSERT INTO MedalTypes (Id, Type) VALUES (50100, N'Azərbaycan Vətən Müharibəsi Veteranları İctimai Birliyinin üzvü');
INSERT INTO MedalTypes (Id, Type) VALUES (50110, N'"AVMVİB-25 il" medalı');
INSERT INTO MedalTypes (Id, Type) VALUES (50200, N'Azərbaycan Qarabağ Müharibəsi Əlilləri, Veteranları və Şəhid Ailələri İctimai Birliyinin üzvü');